### ISSUE TITLE
Can't put macro inside first argument of `default_env!`

### ISSUE THREAD

**Issue by spenserblack** [nhynes/default-env#1]
If the first argument in `default_env!` is a macro that would expand to a literal string, it fails to compile.

# Example

```rust
use default_env::default_env;

const THING: &str = default_env!(stringify!(THING), "default"); // compiler error
```

Could this crate accept macro calls in the first argument as well? Because I love macros in my macros :laughing:

**Comment by nhynes** [comment]
Thanks for the feature request! Unfortunately, proc macros only have access to syntax and can't actually evaluate exprs (you'd need a compiler plugin to do that, and those are not user-friendly). `default_env!` actually reads the env var itself, so it can't dump the `ExprMac` and let rustc handle it either. I'm sorry that you can't macro-in-macro for ALL the positional arguments 😞

Unless you restructure your macro such that it generates a fully-baked invocation of `default_env`, you might just have to use `option_env!` and unwrap everywhere.

**Comment by spenserblack** [comment]
Understood, thanks for the response!
`option_env!` will help once `unwrap_or` becomes a `const fn` :+1:
